### PR TITLE
Add comparison to "Variational order for forced Lagrangian systems"

### PR DESCRIPTION
**Pull request by mseri**
Add second order discretization of a general linearly damped system from Verlet discretization, using the construction from

D Martin de Diego and R Sato Martin de Almagro. Variational order for forced Lagrangian systems. Nonlinearity, Volume 31, Number 8 (2018)

And use it for the comparisons.

### CODE REVIEW

**Comment by mseri** [comment]
You can check the new notebook here: https://github.com/mseri/contact-variational-integrator/blob/variational_noncontact/DampedOscillator.ipynb

**Comment by mvermeeren** [comment]
I've removed an unused argument in variational_noncontact and added forcing terms to the method.

**Comment by mvermeeren** [comment]
I'm getting the following unrelated error:
AttributeError: module 'matplotlib.pylab' has no attribute 'rk4'

It seems that this method is no longer available:
https://matplotlib.org/api/prev_api_changes/api_changes_3.1.0.html?highlight=rk4

We might have to implement rk4 by hand :-/

**Comment by mseri** [comment]
Thanks! I’ll generate and add the forced images, then merge

**Comment by mseri** [comment]
Yes, I know they were deprecating that rk4 implementations. We could vendor it from the old matplotlib sources in case, but our requirements.txt should still point at a version thst includes it

**Pull request merged**
